// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: locations.sql

package locationsdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listAdminAreas = `-- name: ListAdminAreas :many
SELECT
  aa.id::text AS id,
  aa.country_code::text AS country_code,
  aa.code,
  aa.name,
  aa.type,
  parent.code AS parent_code,
  concat_ws(', ', aa.name, upper(aa.country_code::text)) AS label,
  ds.key AS source,
  aa.source_version,
  CASE
    WHEN $1::text = '' THEN 0::float8
    ELSE similarity(public.normalize_location_text(aa.name), public.normalize_location_text($1::text))::float8
  END AS score
FROM admin_areas aa
LEFT JOIN admin_areas parent ON parent.id = aa.parent_id
JOIN data_sources ds ON ds.id = aa.source_id
WHERE aa.country_code = upper($2::text)
  AND ($3::text = '' OR parent.code = $3::text)
  AND ($4::text = '' OR aa.type = $4::text)
  AND (
    $1::text = ''
    OR public.normalize_location_text(aa.name) LIKE '%' || public.normalize_location_text($1::text) || '%'
    OR similarity(public.normalize_location_text(aa.name), public.normalize_location_text($1::text)) > 0.2
  )
ORDER BY score DESC, aa.name ASC
LIMIT $5::int
`

type ListAdminAreasParams struct {
	Query       string `json:"query"`
	CountryCode string `json:"country_code"`
	ParentCode  string `json:"parent_code"`
	TypeFilter  string `json:"type_filter"`
	LimitCount  int32  `json:"limit_count"`
}

type ListAdminAreasRow struct {
	ID            string      `json:"id"`
	CountryCode   string      `json:"country_code"`
	Code          string      `json:"code"`
	Name          string      `json:"name"`
	Type          string      `json:"type"`
	ParentCode    pgtype.Text `json:"parent_code"`
	Label         string      `json:"label"`
	Source        string      `json:"source"`
	SourceVersion string      `json:"source_version"`
	Score         float64     `json:"score"`
}

func (q *Queries) ListAdminAreas(ctx context.Context, arg ListAdminAreasParams) ([]ListAdminAreasRow, error) {
	rows, err := q.db.Query(ctx, listAdminAreas,
		arg.Query,
		arg.CountryCode,
		arg.ParentCode,
		arg.TypeFilter,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminAreasRow{}
	for rows.Next() {
		var i ListAdminAreasRow
		if err := rows.Scan(
			&i.ID,
			&i.CountryCode,
			&i.Code,
			&i.Name,
			&i.Type,
			&i.ParentCode,
			&i.Label,
			&i.Source,
			&i.SourceVersion,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCountries = `-- name: ListCountries :many
SELECT
  c.country_code::text AS country_code,
  c.name,
  c.name AS label,
  ds.key AS source,
  c.source_version,
  CASE
    WHEN $1::text = '' THEN 0::float8
    ELSE similarity(public.normalize_location_text(c.name), public.normalize_location_text($1::text))::float8
  END AS score
FROM countries c
JOIN data_sources ds ON ds.id = c.source_id
WHERE (
    $1::text = ''
    OR public.normalize_location_text(c.name) LIKE '%' || public.normalize_location_text($1::text) || '%'
    OR similarity(public.normalize_location_text(c.name), public.normalize_location_text($1::text)) > 0.2
  )
ORDER BY score DESC, c.name ASC
LIMIT $2::int
`

type ListCountriesParams struct {
	Query      string `json:"query"`
	LimitCount int32  `json:"limit_count"`
}

type ListCountriesRow struct {
	CountryCode   string  `json:"country_code"`
	Name          string  `json:"name"`
	Label         string  `json:"label"`
	Source        string  `json:"source"`
	SourceVersion string  `json:"source_version"`
	Score         float64 `json:"score"`
}

func (q *Queries) ListCountries(ctx context.Context, arg ListCountriesParams) ([]ListCountriesRow, error) {
	rows, err := q.db.Query(ctx, listCountries, arg.Query, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCountriesRow{}
	for rows.Next() {
		var i ListCountriesRow
		if err := rows.Scan(
			&i.CountryCode,
			&i.Name,
			&i.Label,
			&i.Source,
			&i.SourceVersion,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocalities = `-- name: ListLocalities :many
SELECT
  l.id::text AS id,
  l.country_code::text AS country_code,
  aa.code AS admin_area_code,
  l.code,
  l.name,
  l.type,
  concat_ws(', ', l.name, aa.name, upper(l.country_code::text)) AS label,
  ds.key AS source,
  l.source_version,
  CASE
    WHEN $1::text = '' THEN 0::float8
    ELSE similarity(public.normalize_location_text(l.name), public.normalize_location_text($1::text))::float8
  END AS score
FROM localities l
JOIN admin_areas aa ON aa.id = l.admin_area_id
JOIN data_sources ds ON ds.id = l.source_id
WHERE l.country_code = upper($2::text)
  AND ($3::text = '' OR aa.code = $3::text)
  AND (
    $1::text = ''
    OR public.normalize_location_text(l.name) LIKE '%' || public.normalize_location_text($1::text) || '%'
    OR similarity(public.normalize_location_text(l.name), public.normalize_location_text($1::text)) > 0.2
  )
ORDER BY score DESC, l.name ASC
LIMIT $4::int
`

type ListLocalitiesParams struct {
	Query         string `json:"query"`
	CountryCode   string `json:"country_code"`
	AdminAreaCode string `json:"admin_area_code"`
	LimitCount    int32  `json:"limit_count"`
}

type ListLocalitiesRow struct {
	ID            string  `json:"id"`
	CountryCode   string  `json:"country_code"`
	AdminAreaCode string  `json:"admin_area_code"`
	Code          string  `json:"code"`
	Name          string  `json:"name"`
	Type          string  `json:"type"`
	Label         string  `json:"label"`
	Source        string  `json:"source"`
	SourceVersion string  `json:"source_version"`
	Score         float64 `json:"score"`
}

func (q *Queries) ListLocalities(ctx context.Context, arg ListLocalitiesParams) ([]ListLocalitiesRow, error) {
	rows, err := q.db.Query(ctx, listLocalities,
		arg.Query,
		arg.CountryCode,
		arg.AdminAreaCode,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLocalitiesRow{}
	for rows.Next() {
		var i ListLocalitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.CountryCode,
			&i.AdminAreaCode,
			&i.Code,
			&i.Name,
			&i.Type,
			&i.Label,
			&i.Source,
			&i.SourceVersion,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSettlements = `-- name: ListSettlements :many
SELECT
  s.id::text AS id,
  s.country_code::text AS country_code,
  aa.code AS admin_area_code,
  l.code AS locality_code,
  pc.postal_code,
  s.name,
  s.settlement_type AS type,
  concat_ws(', ', s.name, s.settlement_type, pc.postal_code, l.name, aa.name) AS label,
  ds.key AS source,
  s.source_version,
  CASE
    WHEN $1::text = '' THEN 0::float8
    ELSE similarity(public.normalize_location_text(s.name), public.normalize_location_text($1::text))::float8
  END AS score
FROM settlements s
JOIN admin_areas aa ON aa.id = s.admin_area_id
LEFT JOIN localities l ON l.id = s.locality_id
LEFT JOIN postal_codes pc ON pc.id = s.postal_code_id
JOIN data_sources ds ON ds.id = s.source_id
WHERE s.country_code = upper($2::text)
  AND ($3::text = '' OR aa.code = $3::text)
  AND ($4::text = '' OR l.code = $4::text)
  AND ($5::text = '' OR pc.postal_code = $5::text)
  AND (
    $1::text = ''
    OR public.normalize_location_text(s.name) LIKE '%' || public.normalize_location_text($1::text) || '%'
    OR similarity(public.normalize_location_text(s.name), public.normalize_location_text($1::text)) > 0.2
  )
ORDER BY score DESC, s.name ASC
LIMIT $6::int
`

type ListSettlementsParams struct {
	Query         string `json:"query"`
	CountryCode   string `json:"country_code"`
	AdminAreaCode string `json:"admin_area_code"`
	LocalityCode  string `json:"locality_code"`
	PostalCode    string `json:"postal_code"`
	LimitCount    int32  `json:"limit_count"`
}

type ListSettlementsRow struct {
	ID            string      `json:"id"`
	CountryCode   string      `json:"country_code"`
	AdminAreaCode string      `json:"admin_area_code"`
	LocalityCode  pgtype.Text `json:"locality_code"`
	PostalCode    pgtype.Text `json:"postal_code"`
	Name          string      `json:"name"`
	Type          string      `json:"type"`
	Label         string      `json:"label"`
	Source        string      `json:"source"`
	SourceVersion string      `json:"source_version"`
	Score         float64     `json:"score"`
}

func (q *Queries) ListSettlements(ctx context.Context, arg ListSettlementsParams) ([]ListSettlementsRow, error) {
	rows, err := q.db.Query(ctx, listSettlements,
		arg.Query,
		arg.CountryCode,
		arg.AdminAreaCode,
		arg.LocalityCode,
		arg.PostalCode,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSettlementsRow{}
	for rows.Next() {
		var i ListSettlementsRow
		if err := rows.Scan(
			&i.ID,
			&i.CountryCode,
			&i.AdminAreaCode,
			&i.LocalityCode,
			&i.PostalCode,
			&i.Name,
			&i.Type,
			&i.Label,
			&i.Source,
			&i.SourceVersion,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPostalCodes = `-- name: SearchPostalCodes :many
SELECT
  pc.postal_code,
  concat_ws(', ', s.name, pc.postal_code, l.name, aa.name, c.name) AS label,
  pc.country_code::text AS country_code,
  c.name AS country_name,
  aa.code AS admin_area_code,
  aa.name AS admin_area_name,
  l.code AS locality_code,
  l.name AS locality_name,
  s.name AS settlement_name,
  s.settlement_type AS settlement_type,
  ds.key AS source,
  pc.source_version,
  CASE
    WHEN pc.postal_code = $1::text THEN 1::float8
    ELSE 0.75::float8
  END AS score
FROM postal_codes pc
JOIN countries c ON c.country_code = pc.country_code
JOIN admin_areas aa ON aa.id = pc.admin_area_id
LEFT JOIN localities l ON l.id = pc.locality_id
LEFT JOIN settlements s ON s.postal_code_id = pc.id
JOIN data_sources ds ON ds.id = pc.source_id
WHERE pc.country_code = upper($2::text)
  AND pc.postal_code LIKE $1::text || '%'
ORDER BY score DESC, pc.postal_code ASC, s.name ASC NULLS LAST
LIMIT $3::int
`

type SearchPostalCodesParams struct {
	PostalCodePrefix string `json:"postal_code_prefix"`
	CountryCode      string `json:"country_code"`
	LimitCount       int32  `json:"limit_count"`
}

type SearchPostalCodesRow struct {
	PostalCode     string      `json:"postal_code"`
	Label          string      `json:"label"`
	CountryCode    string      `json:"country_code"`
	CountryName    string      `json:"country_name"`
	AdminAreaCode  string      `json:"admin_area_code"`
	AdminAreaName  string      `json:"admin_area_name"`
	LocalityCode   pgtype.Text `json:"locality_code"`
	LocalityName   pgtype.Text `json:"locality_name"`
	SettlementName pgtype.Text `json:"settlement_name"`
	SettlementType pgtype.Text `json:"settlement_type"`
	Source         string      `json:"source"`
	SourceVersion  string      `json:"source_version"`
	Score          float64     `json:"score"`
}

func (q *Queries) SearchPostalCodes(ctx context.Context, arg SearchPostalCodesParams) ([]SearchPostalCodesRow, error) {
	rows, err := q.db.Query(ctx, searchPostalCodes, arg.PostalCodePrefix, arg.CountryCode, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchPostalCodesRow{}
	for rows.Next() {
		var i SearchPostalCodesRow
		if err := rows.Scan(
			&i.PostalCode,
			&i.Label,
			&i.CountryCode,
			&i.CountryName,
			&i.AdminAreaCode,
			&i.AdminAreaName,
			&i.LocalityCode,
			&i.LocalityName,
			&i.SettlementName,
			&i.SettlementType,
			&i.Source,
			&i.SourceVersion,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const suggestAddresses = `-- name: SuggestAddresses :many
SELECT
  concat_ws(', ', st.name, s.name, pc.postal_code, l.name, aa.name, c.name) AS label,
  s.country_code::text AS country_code,
  c.name AS country_name,
  aa.code AS admin_area_code,
  aa.name AS admin_area_name,
  l.code AS locality_code,
  l.name AS locality_name,
  pc.postal_code,
  s.name AS settlement_name,
  s.settlement_type AS settlement_type,
  st.name AS street_name,
  ds.key AS source,
  s.source_version,
  CASE
    WHEN $1::text = '' THEN 0::float8
    ELSE GREATEST(
      similarity(public.normalize_location_text(s.name), public.normalize_location_text($1::text)),
      similarity(public.normalize_location_text(coalesce(st.name, '')), public.normalize_location_text($1::text)),
      similarity(public.normalize_location_text(coalesce(l.name, '')), public.normalize_location_text($1::text)),
      similarity(public.normalize_location_text(aa.name), public.normalize_location_text($1::text))
    )::float8
  END AS score
FROM settlements s
JOIN countries c ON c.country_code = s.country_code
JOIN admin_areas aa ON aa.id = s.admin_area_id
LEFT JOIN localities l ON l.id = s.locality_id
LEFT JOIN postal_codes pc ON pc.id = s.postal_code_id
LEFT JOIN streets st ON st.settlement_id = s.id
JOIN data_sources ds ON ds.id = s.source_id
WHERE s.country_code = upper($2::text)
  AND ($3::text = '' OR pc.postal_code = $3::text)
  AND (
    $1::text = ''
    OR public.normalize_location_text(s.name) LIKE '%' || public.normalize_location_text($1::text) || '%'
    OR public.normalize_location_text(coalesce(st.name, '')) LIKE '%' || public.normalize_location_text($1::text) || '%'
    OR public.normalize_location_text(coalesce(l.name, '')) LIKE '%' || public.normalize_location_text($1::text) || '%'
    OR public.normalize_location_text(aa.name) LIKE '%' || public.normalize_location_text($1::text) || '%'
    OR similarity(public.normalize_location_text(s.name), public.normalize_location_text($1::text)) > 0.2
    OR similarity(public.normalize_location_text(coalesce(st.name, '')), public.normalize_location_text($1::text)) > 0.2
    OR similarity(public.normalize_location_text(coalesce(l.name, '')), public.normalize_location_text($1::text)) > 0.2
    OR similarity(public.normalize_location_text(aa.name), public.normalize_location_text($1::text)) > 0.2
  )
ORDER BY score DESC, label ASC
LIMIT $4::int
`

type SuggestAddressesParams struct {
	Query       string `json:"query"`
	CountryCode string `json:"country_code"`
	PostalCode  string `json:"postal_code"`
	LimitCount  int32  `json:"limit_count"`
}

type SuggestAddressesRow struct {
	Label          string      `json:"label"`
	CountryCode    string      `json:"country_code"`
	CountryName    string      `json:"country_name"`
	AdminAreaCode  string      `json:"admin_area_code"`
	AdminAreaName  string      `json:"admin_area_name"`
	LocalityCode   pgtype.Text `json:"locality_code"`
	LocalityName   pgtype.Text `json:"locality_name"`
	PostalCode     pgtype.Text `json:"postal_code"`
	SettlementName string      `json:"settlement_name"`
	SettlementType string      `json:"settlement_type"`
	StreetName     pgtype.Text `json:"street_name"`
	Source         string      `json:"source"`
	SourceVersion  string      `json:"source_version"`
	Score          float64     `json:"score"`
}

func (q *Queries) SuggestAddresses(ctx context.Context, arg SuggestAddressesParams) ([]SuggestAddressesRow, error) {
	rows, err := q.db.Query(ctx, suggestAddresses,
		arg.Query,
		arg.CountryCode,
		arg.PostalCode,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SuggestAddressesRow{}
	for rows.Next() {
		var i SuggestAddressesRow
		if err := rows.Scan(
			&i.Label,
			&i.CountryCode,
			&i.CountryName,
			&i.AdminAreaCode,
			&i.AdminAreaName,
			&i.LocalityCode,
			&i.LocalityName,
			&i.PostalCode,
			&i.SettlementName,
			&i.SettlementType,
			&i.StreetName,
			&i.Source,
			&i.SourceVersion,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
