// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package locationsdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AdminArea struct {
	ID             pgtype.UUID        `json:"id"`
	CountryCode    string             `json:"country_code"`
	ParentID       pgtype.UUID        `json:"parent_id"`
	Code           string             `json:"code"`
	Name           string             `json:"name"`
	Type           string             `json:"type"`
	SourceID       pgtype.UUID        `json:"source_id"`
	SourceRecordID pgtype.Text        `json:"source_record_id"`
	SourceVersion  string             `json:"source_version"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Country struct {
	ID             pgtype.UUID        `json:"id"`
	CountryCode    string             `json:"country_code"`
	Name           string             `json:"name"`
	SourceID       pgtype.UUID        `json:"source_id"`
	SourceRecordID pgtype.Text        `json:"source_record_id"`
	SourceVersion  string             `json:"source_version"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type DataSource struct {
	ID          pgtype.UUID        `json:"id"`
	Key         string             `json:"key"`
	Name        string             `json:"name"`
	Version     string             `json:"version"`
	License     string             `json:"license"`
	Attribution string             `json:"attribution"`
	Url         pgtype.Text        `json:"url"`
	ImportedAt  pgtype.Timestamptz `json:"imported_at"`
}

type Locality struct {
	ID             pgtype.UUID        `json:"id"`
	CountryCode    string             `json:"country_code"`
	AdminAreaID    pgtype.UUID        `json:"admin_area_id"`
	Code           string             `json:"code"`
	Name           string             `json:"name"`
	Type           string             `json:"type"`
	SourceID       pgtype.UUID        `json:"source_id"`
	SourceRecordID pgtype.Text        `json:"source_record_id"`
	SourceVersion  string             `json:"source_version"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type PostalCode struct {
	ID             pgtype.UUID        `json:"id"`
	CountryCode    string             `json:"country_code"`
	AdminAreaID    pgtype.UUID        `json:"admin_area_id"`
	LocalityID     pgtype.UUID        `json:"locality_id"`
	PostalCode     string             `json:"postal_code"`
	SourceID       pgtype.UUID        `json:"source_id"`
	SourceRecordID pgtype.Text        `json:"source_record_id"`
	SourceVersion  string             `json:"source_version"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Settlement struct {
	ID             pgtype.UUID        `json:"id"`
	CountryCode    string             `json:"country_code"`
	AdminAreaID    pgtype.UUID        `json:"admin_area_id"`
	LocalityID     pgtype.UUID        `json:"locality_id"`
	PostalCodeID   pgtype.UUID        `json:"postal_code_id"`
	Code           pgtype.Text        `json:"code"`
	Name           string             `json:"name"`
	SettlementType string             `json:"settlement_type"`
	SourceID       pgtype.UUID        `json:"source_id"`
	SourceRecordID pgtype.Text        `json:"source_record_id"`
	SourceVersion  string             `json:"source_version"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Street struct {
	ID             pgtype.UUID        `json:"id"`
	CountryCode    string             `json:"country_code"`
	AdminAreaID    pgtype.UUID        `json:"admin_area_id"`
	LocalityID     pgtype.UUID        `json:"locality_id"`
	SettlementID   pgtype.UUID        `json:"settlement_id"`
	Name           string             `json:"name"`
	SourceID       pgtype.UUID        `json:"source_id"`
	SourceRecordID pgtype.Text        `json:"source_record_id"`
	SourceVersion  string             `json:"source_version"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}
